# Generated by Django 5.0.3 on 2024-03-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sell_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField(default='')),
                ('composition', models.TextField()),
                ('cetagory', models.CharField(choices=[('LP', 'Laptop'), ('MB', 'Mobile'), ('TB', 'Tablet'), ('LD', 'Led'), ('HP', 'HeadPhone')], max_length=2)),
                ('product_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
